#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR
if [ ! -d gradle-2.6 ]
then
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.6-bin.zip
    unzip gradle-2.6-bin.zip
    rm -f gradle-2.6-bin.zip
fi
if [ ! -d jdk1.8.0_05 ]
then
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    tar -zxf jdk-8u5-linux-x64.tar.gz
    export JAVA_HOME="OPENSHIFT_DATA_DIR/jdk1.8.0_05"
    export PATH="$JAVA_HOME/bin:$PATH"
fi
