#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR
if [ ! -d gradle-2.6 ]
then
    mkdir gradle
    cd gradle
    curl -L  http://services.gradle.org/distributions/gradle-2.6-bin.zip | python -c "import zipfile,sys,StringIO;zipfile.ZipFile(StringIO.StringIO(sys.stdin.read())).extractall('.')"
    cd ..
fi
if [ ! -d jdk1.8.0_05 ]
then
    curl -L --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz | tar -zxf -
fi
