#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR
if [ ! -d jdk1.8.0_05 ]
then
    curl -L --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz | tar -zxf -
fi
