spring:
  application:
    name: WeTrackPro - Thermo
  datasource:
    url: jdbc:hsqldb:file:/tmp/wetrackpro/parker
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  jackson.serialization:
    ORDER_MAP_ENTRIES_BY_KEYS: true
    INDENT_OUTPUT: true
  resources.cache-period: 86400
  http.encoding.charset: UTF-8
  thymeleaf.cache: false
  mvc.favicon.enabled: false
management.context-path: /management
logging:
  path: /tmp/wetrackpro/
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  check-change-log-location: false
  enabled: true
endpoints.shutdown.enabled: true