spring:
  jpa:
    hibernate.ddl-auto: update
  resources.cache-period: 86400
  http.encoding.charset: UTF-8
  thymeleaf.cache: true
  datasource:
    url: jdbc:postgresql://${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/feverd
    username: ${OPENSHIFT_POSTGRESQL_DB_USERNAME}
    password: ${OPENSHIFT_POSTGRESQL_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
server:
  address: ${OPENSHIFT_DIY_IP}
  port: ${OPENSHIFT_DIY_PORT}
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
logging:
  path: ${OPENSHIFT_DATA_DIR}/logs/