spring:
  application:
    name: WeTrackPro - Thermo
  datasource:
    url: jdbc:hsqldb:file:/tmp/wetrackpro/parker
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
  jackson.serialization:
    ORDER_MAP_ENTRIES_BY_KEYS: true
    INDENT_OUTPUT: true
  resources.cache-period: 86400
  http.encoding.charset: UTF-8
  thymeleaf.cache: false
  mvc.favicon.enabled: false
management.context-path: /management
logging:
  path: /tmp/wetrackpro/
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  check-change-log-location: false
  enabled: true
endpoints.shutdown.enabled: true

#security.user.name: user # login username
#security.user.password: # login password
#security.user.role: USER # role assigned to the user
#security.require-ssl: false # advanced settings ...
#security.enable-csrf: false
#security.basic.enabled: true
#security.basic.realm: Spring
#security.basic.path: /management
#security.basic.authorize-mode: ROLE, AUTHENTICATED, NONE
#security.filter-order: 0
#security.headers.xss: false
#security.headers.cache: false
#security.headers.frame: false
#security.headers.content-type: false
#security.headers.hsts: all
#security.sessions: stateless # always / never / if_required / stateless
#security.ignored: # Comma-separated list of paths to exclude from the default secured paths
#shell.auth: simple # jaas, key, simple, spring
#shell.command-refresh-interval: -1
#shell.command-path-patterns: # classpath*:/commands/**, classpath*:/crash/commands/**
#shell.config-path-patterns: # classpath*:/crash/*
#shell.disabled-commands: jpa*,jdbc*,jndi* # comma-separated list of commands to disable
#shell.disabled-plugins: false # don't expose plugins
#shell.ssh.enabled: # ssh settings ...
#shell.ssh.key-path:
#shell.ssh.port:
#shell.telnet.enabled: # telnet settings ...
#shell.telnet.port:
#shell.auth.jaas.domai: # authentication settings ...
#shell.auth.key.path:
#shell.auth.simple.user.name:
#shell.auth.simple.user.password:
#shell.auth.spring.roles:
