spring:
  application:
    name: WeTrackPro - Thermo
  datasource:
    url: jdbc:mysql://${MYSQL_PORT_3306_TCP_ADDR}:${MYSQL_PORT_3306_TCP_PORT}/${MYSQL_ENV_MYSQL_DATABASE}
    username: ${MYSQL_ENV_MYSQL_USER}
    password: ${MYSQL_ENV_MYSQL_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    hibernate.dialect: MySQL
    show-sql: false
  jackson.serialization:
    ORDER_MAP_ENTRIES_BY_KEYS: false
    INDENT_OUTPUT: false
  resources.cache-period: 86400
  http.encoding.charset: UTF-8
  thymeleaf.cache: true
  mvc.favicon.enabled: false
management.context-path: /management
logging:
  path: /var/log/feverd/
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
  check-change-log-location: false
  enabled: false
endpoints.shutdown.enabled: true
